WebApplications/Bootstrap/WebApplication/Controllers/FormsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication.Controllers
{
    public class FormsController : Controller
    {
      
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Details()
        {
            return View();
        }
    }
}

WebApplications/Bootstrap/WebApplication/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyWebApplication.Controllers
{
    public class HomeController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }


        public ActionResult Annunci()
        {
            return View();
        }
    }
}

WebApplications/Bootstrap/WebApplication/Controllers/TableController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication.Controllers
{
    public class TableController : Controller
    {
      
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Test01()
        {
            return View();
        }
    }
}

WebApplications/Bootstrap/WebApplication/Views/Forms/Details.cshtml
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/MasterPageBootstrap.cshtml";
}

<h2>Details</h2>


<form class="form-inline">
    <div class="form-group">
        <label>Nome</label>
        <span>Roberto</span>
    </div>

    <div class="form-group">
        <label>Cognome</label>
        <span>Rutigliano</span>
    </div>


    <div class="form-group">
        <label>Email</label>
        <span>roberto.rutiglianogmail.com</span>
    </div>
</form>

<hr />

<div class="container-fluid">
    <div class="row">
        <div class="col-md-4"><label>Nome</label></div>
        <div class="col-md-8">Roberto</div>
    </div>
    
    <div class="row">
        <div class="col-md-4"><label>Cognome</label></div>
        <div class="col-md-8">Rutigliano</div>
    </div>

    <div class="row">
        <div class="col-md-4"><label>Indirizzo per la spedizione</label></div>
        <div class="col-md-8">Via del Trullo, 150 - 00100 - Roma (RM)</div>
    </div>

    <div class="row">
        <div class="col-md-4"><label>Email</label></div>
        <div class="col-md-8">roberto.rutigliano</div>
    </div>
</div>

<hr />

<div class="container-fluid">
    <div class="row">
        <div class="col-xs-4"><label>Nome</label></div>
        <div class="col-xs-8">Roberto</div>
    </div>


    <div class="row">
        <div class="col-xs-4"><label>Cognome</label></div>
        <div class="col-xs-8">Rutigliano</div>
    </div>

    <div class="row">
        <div class="col-xs-4"><label>Indirizzo per la spedizione</label></div>
        <div class="col-xs-8">Via del Trullo, 150 - 00100 - Roma (RM)</div>
    </div>

    <div class="row">
        <div class="col-xs-4"><label>Email</label></div>
        <div class="col-xs-8">roberto.rutigliano</div>
    </div>
</div>

WebApplications/Bootstrap/WebApplication/Views/Forms/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/MasterPageBootstrap.cshtml";
}

<h2>Index</h2>


<div class="list-group">
    <a href="@Url.Action("Details")" class="list-group-item">Details</a>
</div>

WebApplications/Bootstrap/WebApplication/Views/Shared/MasterPageBootstrap.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->


    <title>@ViewBag.Title</title>

    <!-- Bootstrap -->
    <link href="@Url.Content("~/Content/bootstrap.min.css")" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="@Url.Content("~/Scripts/jquery-2.2.3.min.js")"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="@Url.Content("~/Scripts/bootstrap.min.js")"></script>
</head>
<body role="document">

    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Project name</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="#">Home</a></li>

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("Annunci")">Annunci</a></li>
                            <li><a href="@Url.Action("Test01","Table")"> Table - Test01</a></li>
                            <li><a href="@Url.Action("Index","Forms")">Forms</a></li>
                            <li role="separator" class="divider"></li>
                            <li class="dropdown-header">Nav header</li>
                            <li><a href="#">Separated link</a></li>
                            <li><a href="#">One more separated link</a></li>
                        </ul>
                    </li>

                    <li><a href="#about">About</a></li>
                    <li><a href="#contact">Contact</a></li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </nav>
    <div class="container theme-showcase" role="main">
        @RenderBody()
    </div>
</body>
</html>

WebApplications/Bootstrap/WebApplication/Views/Table/Test01.cshtml
@{
    ViewBag.Title = "Test01";
    Layout = "~/Views/Shared/MasterPageBootstrap.cshtml";
}

<h2>Test01</h2>

<table class="table table-hover table-striped">
    <thead>
        <tr>
            <th>#</th>
            <th>Login</th>
            <th>Nome</th>
            <th>Cognome</th>
        </tr>
    </thead>
    <tfoot>
        <tr>
            <td colspan="4">
                FOOTER
            </td>
        </tr>
    </tfoot>

    <tbody>
        <tr>
            <td>1</td>
            <td>roberto.rutigliano</td>
            <td>Roberto</td>
            <td>Rutigliano</td>
        </tr>
    </tbody>
</table>